name: CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest, windows-latest]
        include: 
          - os: ubuntu-latest
            node: '16.x'
            upload: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies ( clean )
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build --if-present

      - name: ls
        run: ls

      - name: Publish 
        if: matrix.upload
        run: npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

              
  


