name: CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies ( clean )
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build --if-present
  
  publish:
    needs: build
    name: Publish to npm
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: ls
        run: ls

      - name: Setup Node 
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Publish
        run: npm publish --access public --ignore-scripts
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            
  


