name: CI
on: 
  push:
    branches: [ master ]
jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            node: '16.x'
            upload: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies ( clean )
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build --if-present

      - name: FS Contents after Build
        run: ls
      
      - name: Upload Artifacts
        if: matrix.upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish:
      name: Publish to npm
      runs-on: ubuntu-latest
      needs: [ build ]

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Download build artifact
          uses: actions/download-artifact@v2
          with:
            name: dist
            path: dist

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org/'
          
        - name: FS Contents
          run: ls

        - name: Publish
          run: npm publish --access public --ignore-scripts
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      

              
  


